### ISSUE TITLE
MultiPoolMiner Version 3 Roadmap

### ISSUE THREAD

**Issue by fonyo** [aaronsace/MultiPoolMiner#378]
# MultiPoolMiner Version 3 Roadmap

### **Core MPM**
- [ ] All tasks are complete and all related issues are closed
     - [ ] LINUX compatibility #104 
     - [ ] Detect and handle failures of miners #130 #377 
     - [ ] Improve failover (pools) #96 #200 #275 
     - [ ] Detect system hardware and handle mining accordingly (ie. mining on older GPUs and CPUs) #241 
     - [ ] Handling of mixed-card-rigs (mixed cards of same brand, mixed cards of AMD and NVIDIA) and excluding certain cards, algorithms, miners on user request #155 #225 #295 #321 
     - [ ] Update documentation to support V3 changes and update FAQ with newly arised questions from the Issues page #94 #278 

### **Profitability & Stats**
- [ ] All tasks are complete and all related issues are closed
     - [ ] Account for losses due to conversion, pool and development fee #35
     - [ ] Implement profitability threshold #242 
     - [ ] Improve profit calculation by accounting for power usage and cost #51 #316 
     - [ ] Improve handling of external data (ie. hiccups caused by false price spikes) #115 
     - [ ] Integrating WattTool profiles and/or enabling custom user commands prior to launching miners (for better overclock and power management per miner) - optional for advanced users #75 #227 
     - [ ] Stats error correction, preventing/handling internal errors #247 #249
     - [ ] User-friendly stats, better organistaion and spacing on display #370 

### **API**
- [ ] All tasks are complete and all related issues are closed
     - [ ] Use miner API where possible to change miner configuration instead of relaunching miner #117 
     - [ ] Create MPM API for overall monitoring (API2API) #216 #340 

### **Clean-up & Testing**
- [ ] All tasks are complete and all related issues are closed
     - [ ] Download/install prerequisite files and other dependencies #74 
     - [ ] Improve codebase where possible #294 
     - [ ] Ensure new functionality is extensively tested and current v2 features are not broken 
     - [ ] Issue public pre-release in order to squash bugs before go-live

**Comment by mlsad3** [comment]
Hi,
What language are you planning to use for this? I had been dabbling in converting some of your stuff into a C# GUI because it seems like an easier interface to work with. Or are you wanting to just keep on with the PowerShell, as it allows easier tinkering by others?

**Comment by jjziets** [comment]
Please add Blake

**Comment by fonyo** [comment]
@mlsad3  As you said, easy user editability is a key advantage of MPM. The CC world is rapidly changing and there are many user who want different and special features that will most likely be **always** out of scope for MPM. 

@jjziets please post a new issue for feature requests.

**Comment by UselessGuru** [comment]
@fonyo 

What about a nice configuration GUI to edit/save all parameters?
Instead of defining everything in start.bat MPM could read its config from the config file created by the GUI.

**Comment by interbiznw** [comment]
> What about a nice configuration GUI to edit/save all parameters?
Instead of defining everything in start.bat MPM could read its config from the config file created by the GUI


Why would someone thumbs down that lol. Personally I think it sounds like a great idea, more user friendly to change the settings, and the GUI Saves the config file which is used behind the scenes interacting with the core program and individual miners

**Comment by Warkdev** [comment]
Hello, is there a need for help for this ? I do have a setup with 2 Nvidia but different GPU (One old, one recent) and I would like them t o be on separated algos whenever they can't mine together.

**Comment by sorryad** [comment]
Росчет потребления наверное самое менее важное что нужно внедрять

**Comment by UselessGuru** [comment]
@Warkdev
> Hello, is there a need for help for this ? I do have a setup with 2 Nvidia but different GPU (One old, one recent) and I would like them t o be on separated algos whenever they can't mine together.

This is implemented in 3.1.0:
https://github.com/MultiPoolMiner/MultiPoolMiner/releases/tag/3.1.0
